#!/bin/zsh
./deterministic_gating_attackTraining_residualVictim.py rotten_tomatoes imdb > data_ign/log/deterministic_gating_attackTraining_residualVictim/imdb_attack_rotten_tomatoes
./deterministic_gating_attackTraining_residualVictim.py sst2 imdb > data_ign/log/deterministic_gating_attackTraining_residualVictim/imdb_attack_sst2
./deterministic_gating_attackTraining_residualVictim.py yelp_polarity imdb > data_ign/log/deterministic_gating_attackTraining_residualVictim/imdb_attack_yelp_polarity
./deterministic_gating_attackTraining_residualVictim.py imdb rotten_tomatoes > data_ign/log/deterministic_gating_attackTraining_residualVictim/rotten_tomatoes_attack_imdb
./deterministic_gating_attackTraining_residualVictim.py sst2 rotten_tomatoes > data_ign/log/deterministic_gating_attackTraining_residualVictim/rotten_tomatoes_attack_sst2
./deterministic_gating_attackTraining_residualVictim.py yelp_polarity rotten_tomatoes > data_ign/log/deterministic_gating_attackTraining_residualVictim/rotten_tomatoes_attack_yelp_polarity
./deterministic_gating_attackTraining_residualVictim.py imdb sst2 > data_ign/log/deterministic_gating_attackTraining_residualVictim/sst2_attack_imdb
./deterministic_gating_attackTraining_residualVictim.py rotten_tomatoes sst2 > data_ign/log/deterministic_gating_attackTraining_residualVictim/sst2_attack_rotten_tomatoes
./deterministic_gating_attackTraining_residualVictim.py yelp_polarity sst2 > data_ign/log/deterministic_gating_attackTraining_residualVictim/sst2_attack_yelp_polarity
./deterministic_gating_attackTraining_residualVictim.py imdb yelp_polarity > data_ign/log/deterministic_gating_attackTraining_residualVictim/yelp_polarity_attack_imdb
./deterministic_gating_attackTraining_residualVictim.py rotten_tomatoes yelp_polarity > data_ign/log/deterministic_gating_attackTraining_residualVictim/yelp_polarity_attack_rotten_tomatoes
./deterministic_gating_attackTraining_residualVictim.py sst2 yelp_polarity > data_ign/log/deterministic_gating_attackTraining_residualVictim/yelp_polarity_attack_sst2