#!/bin/zsh

./offensive_residualVictim_attackTraining.py olid_processed toxic_conversations_50k > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case1_offensive_residualVictim_attackTraining/toxic_conversations_50k_attack_olid_processed
./offensive_residualVictim_attackTraining.py hate_speech_offensive toxic_conversations_50k > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case1_offensive_residualVictim_attackTraining/toxic_conversations_50k_attack_hate_speech_offensive
./offensive_residualVictim_attackTraining.py hate_speech18 toxic_conversations_50k > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case1_offensive_residualVictim_attackTraining/toxic_conversations_50k_attack_hate_speech18

./offensive_residualVictim_attackEvaluation.py olid_processed toxic_conversations_50k > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case1_offensive_residualVictim_attackEvaluation/toxic_conversations_50k_attack_olid_processed
./offensive_residualVictim_attackEvaluation.py hate_speech_offensive toxic_conversations_50k > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case1_offensive_residualVictim_attackEvaluation/toxic_conversations_50k_attack_hate_speech_offensive
./offensive_residualVictim_attackEvaluation.py hate_speech18 toxic_conversations_50k > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case1_offensive_residualVictim_attackEvaluation/toxic_conversations_50k_attack_hate_speech18
