#!/bin/zsh

# ./sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf.py sst2 1000 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf/sst2_attack_sentiment
# ./sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf.py sst2 5000 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf/sst2_attack_sentiment
# ./sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf.py sst2 10000 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf/sst2_attack_sentiment
# ./sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf.py sst2 20000 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf/sst2_attack_sentiment

# ./sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf.py imdb 50000 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf/imdb_attack_sentiment
./sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf.py rotten_tomatoes 50000 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf/rotten_tomatoes_attack_sentiment
./sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf.py sst2 50000 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf/sst2_attack_sentiment
./sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf.py yelp_polarity 50000 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackEvaluation_withGatingNetworkSelf/yelp_polarity_attack_sentiment