#!/bin/zsh
./sentiment_backdoorExpert_attackTraining.py imdb > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackTraining/imdb_backdoorExpert_attack_sentiment
./sentiment_backdoorExpert_attackTraining.py rotten_tomatoes > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackTraining/rotten_tomatoes_backdoorExpert_attack_sentiment
./sentiment_backdoorExpert_attackTraining.py sst2 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackTraining/sst2_backdoorExpert_attack_sentiment
./sentiment_backdoorExpert_attackTraining.py yelp_polarity > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorExpert_attackTraining/yelp_polarity_backdoorExpert_attack_sentiment

./sentiment_backdoorGatingNetwork_attackTraining.py 0.1 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorGatingNetwork_attackTraining/yelp_polarity_backdoorGatingNetwork_attack_sentiment
./sentiment_backdoorGatingNetwork_attackTraining.py 0.2 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorGatingNetwork_attackTraining/yelp_polarity_backdoorGatingNetwork_attack_sentiment
./sentiment_backdoorGatingNetwork_attackTraining.py 0.3 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorGatingNetwork_attackTraining/yelp_polarity_backdoorGatingNetwork_attack_sentiment
./sentiment_backdoorGatingNetwork_attackTraining.py 0.4 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorGatingNetwork_attackTraining/yelp_polarity_backdoorGatingNetwork_attack_sentiment
./sentiment_backdoorGatingNetwork_attackTraining.py 0.5 > /home/jaehan/research/adapter/adapter-poisoning/data_ign/log/case2_sentiment_backdoorGatingNetwork_attackTraining/yelp_polarity_backdoorGatingNetwork_attack_sentiment